package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DayClosureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayClosureAllPropertiesEquals(DayClosure expected, DayClosure actual) {
        assertDayClosureAutoGeneratedPropertiesEquals(expected, actual);
        assertDayClosureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayClosureAllUpdatablePropertiesEquals(DayClosure expected, DayClosure actual) {
        assertDayClosureUpdatableFieldsEquals(expected, actual);
        assertDayClosureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayClosureAutoGeneratedPropertiesEquals(DayClosure expected, DayClosure actual) {
        assertThat(expected)
            .as("Verify DayClosure auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayClosureUpdatableFieldsEquals(DayClosure expected, DayClosure actual) {
        assertThat(expected)
            .as("Verify DayClosure relevant properties")
            .satisfies(e -> assertThat(e.getBusinessDate()).as("check businessDate").isEqualTo(actual.getBusinessDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e ->
                assertThat(e.getConfirmedByUsername()).as("check confirmedByUsername").isEqualTo(actual.getConfirmedByUsername())
            )
            .satisfies(e -> assertThat(e.getConfirmedAt()).as("check confirmedAt").isEqualTo(actual.getConfirmedAt()))
            .satisfies(e -> assertThat(e.getReopenedByUsername()).as("check reopenedByUsername").isEqualTo(actual.getReopenedByUsername()))
            .satisfies(e -> assertThat(e.getReopenedAt()).as("check reopenedAt").isEqualTo(actual.getReopenedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayClosureUpdatableRelationshipsEquals(DayClosure expected, DayClosure actual) {
        assertThat(expected)
            .as("Verify DayClosure relationships")
            .satisfies(e -> assertThat(e.getOffice()).as("check office").isEqualTo(actual.getOffice()));
    }
}
