package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DoorFeeRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoorFeeRuleAllPropertiesEquals(DoorFeeRule expected, DoorFeeRule actual) {
        assertDoorFeeRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertDoorFeeRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoorFeeRuleAllUpdatablePropertiesEquals(DoorFeeRule expected, DoorFeeRule actual) {
        assertDoorFeeRuleUpdatableFieldsEquals(expected, actual);
        assertDoorFeeRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoorFeeRuleAutoGeneratedPropertiesEquals(DoorFeeRule expected, DoorFeeRule actual) {
        assertThat(expected)
            .as("Verify DoorFeeRule auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoorFeeRuleUpdatableFieldsEquals(DoorFeeRule expected, DoorFeeRule actual) {
        assertThat(expected)
            .as("Verify DoorFeeRule relevant properties")
            .satisfies(e -> assertThat(e.getKind()).as("check kind").isEqualTo(actual.getKind()))
            .satisfies(e -> assertThat(e.getMinKg()).as("check minKg").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getMinKg()))
            .satisfies(e -> assertThat(e.getMaxKg()).as("check maxKg").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getMaxKg()))
            .satisfies(e -> assertThat(e.getMinKm()).as("check minKm").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getMinKm()))
            .satisfies(e -> assertThat(e.getMaxKm()).as("check maxKm").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getMaxKm()))
            .satisfies(e ->
                assertThat(e.getFeeAmount()).as("check feeAmount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getFeeAmount())
            )
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoorFeeRuleUpdatableRelationshipsEquals(DoorFeeRule expected, DoorFeeRule actual) {
        // empty method
    }
}
