package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntegrationConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrationConfigAllPropertiesEquals(IntegrationConfig expected, IntegrationConfig actual) {
        assertIntegrationConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertIntegrationConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrationConfigAllUpdatablePropertiesEquals(IntegrationConfig expected, IntegrationConfig actual) {
        assertIntegrationConfigUpdatableFieldsEquals(expected, actual);
        assertIntegrationConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrationConfigAutoGeneratedPropertiesEquals(IntegrationConfig expected, IntegrationConfig actual) {
        assertThat(expected)
            .as("Verify IntegrationConfig auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrationConfigUpdatableFieldsEquals(IntegrationConfig expected, IntegrationConfig actual) {
        assertThat(expected)
            .as("Verify IntegrationConfig relevant properties")
            .satisfies(e -> assertThat(e.getAhamoveToken()).as("check ahamoveToken").isEqualTo(actual.getAhamoveToken()))
            .satisfies(e -> assertThat(e.getGrabToken()).as("check grabToken").isEqualTo(actual.getGrabToken()))
            .satisfies(e -> assertThat(e.getXanhsmToken()).as("check xanhsmToken").isEqualTo(actual.getXanhsmToken()))
            .satisfies(e -> assertThat(e.getDistanceApiToken()).as("check distanceApiToken").isEqualTo(actual.getDistanceApiToken()))
            .satisfies(e -> assertThat(e.getTelegramToken()).as("check telegramToken").isEqualTo(actual.getTelegramToken()))
            .satisfies(e -> assertThat(e.getTelegramChatId()).as("check telegramChatId").isEqualTo(actual.getTelegramChatId()))
            .satisfies(e -> assertThat(e.getWebhookUrl()).as("check webhookUrl").isEqualTo(actual.getWebhookUrl()))
            .satisfies(e -> assertThat(e.getWebhookSecret()).as("check webhookSecret").isEqualTo(actual.getWebhookSecret()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrationConfigUpdatableRelationshipsEquals(IntegrationConfig expected, IntegrationConfig actual) {
        // empty method
    }
}
