package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OfficeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeAllPropertiesEquals(Office expected, Office actual) {
        assertOfficeAutoGeneratedPropertiesEquals(expected, actual);
        assertOfficeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeAllUpdatablePropertiesEquals(Office expected, Office actual) {
        assertOfficeUpdatableFieldsEquals(expected, actual);
        assertOfficeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeAutoGeneratedPropertiesEquals(Office expected, Office actual) {
        assertThat(expected)
            .as("Verify Office auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeUpdatableFieldsEquals(Office expected, Office actual) {
        assertThat(expected)
            .as("Verify Office relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getOfficeType()).as("check officeType").isEqualTo(actual.getOfficeType()))
            .satisfies(e -> assertThat(e.getIsHub()).as("check isHub").isEqualTo(actual.getIsHub()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficeUpdatableRelationshipsEquals(Office expected, Office actual) {
        // empty method
    }
}
