package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OrderFareAdjustmentRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderFareAdjustmentRequestAllPropertiesEquals(
        OrderFareAdjustmentRequest expected,
        OrderFareAdjustmentRequest actual
    ) {
        assertOrderFareAdjustmentRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderFareAdjustmentRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderFareAdjustmentRequestAllUpdatablePropertiesEquals(
        OrderFareAdjustmentRequest expected,
        OrderFareAdjustmentRequest actual
    ) {
        assertOrderFareAdjustmentRequestUpdatableFieldsEquals(expected, actual);
        assertOrderFareAdjustmentRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderFareAdjustmentRequestAutoGeneratedPropertiesEquals(
        OrderFareAdjustmentRequest expected,
        OrderFareAdjustmentRequest actual
    ) {
        assertThat(expected)
            .as("Verify OrderFareAdjustmentRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderFareAdjustmentRequestUpdatableFieldsEquals(
        OrderFareAdjustmentRequest expected,
        OrderFareAdjustmentRequest actual
    ) {
        assertThat(expected)
            .as("Verify OrderFareAdjustmentRequest relevant properties")
            .satisfies(e ->
                assertThat(e.getRequestedFareAmount())
                    .as("check requestedFareAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getRequestedFareAmount())
            )
            .satisfies(e -> assertThat(e.getReason()).as("check reason").isEqualTo(actual.getReason()))
            .satisfies(e ->
                assertThat(e.getRequestedByUsername()).as("check requestedByUsername").isEqualTo(actual.getRequestedByUsername())
            )
            .satisfies(e -> assertThat(e.getRequestedAt()).as("check requestedAt").isEqualTo(actual.getRequestedAt()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getApprovedByUsername()).as("check approvedByUsername").isEqualTo(actual.getApprovedByUsername()))
            .satisfies(e -> assertThat(e.getApprovedAt()).as("check approvedAt").isEqualTo(actual.getApprovedAt()))
            .satisfies(e -> assertThat(e.getRejectedByUsername()).as("check rejectedByUsername").isEqualTo(actual.getRejectedByUsername()))
            .satisfies(e -> assertThat(e.getRejectedAt()).as("check rejectedAt").isEqualTo(actual.getRejectedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderFareAdjustmentRequestUpdatableRelationshipsEquals(
        OrderFareAdjustmentRequest expected,
        OrderFareAdjustmentRequest actual
    ) {
        // empty method
    }
}
