package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OrderPaymentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPaymentAllPropertiesEquals(OrderPayment expected, OrderPayment actual) {
        assertOrderPaymentAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderPaymentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPaymentAllUpdatablePropertiesEquals(OrderPayment expected, OrderPayment actual) {
        assertOrderPaymentUpdatableFieldsEquals(expected, actual);
        assertOrderPaymentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPaymentAutoGeneratedPropertiesEquals(OrderPayment expected, OrderPayment actual) {
        assertThat(expected)
            .as("Verify OrderPayment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPaymentUpdatableFieldsEquals(OrderPayment expected, OrderPayment actual) {
        assertThat(expected)
            .as("Verify OrderPayment relevant properties")
            .satisfies(e -> assertThat(e.getPaymentAt()).as("check paymentAt").isEqualTo(actual.getPaymentAt()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getMethod()).as("check method").isEqualTo(actual.getMethod()))
            .satisfies(e -> assertThat(e.getPaymentKind()).as("check paymentKind").isEqualTo(actual.getPaymentKind()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()))
            .satisfies(e -> assertThat(e.getCollectorUsername()).as("check collectorUsername").isEqualTo(actual.getCollectorUsername()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPaymentUpdatableRelationshipsEquals(OrderPayment expected, OrderPayment actual) {
        assertThat(expected)
            .as("Verify OrderPayment relationships")
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()));
    }
}
