package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderDeliveryAttemptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderDeliveryAttemptAllPropertiesEquals(OrderDeliveryAttempt expected, OrderDeliveryAttempt actual) {
        assertOrderDeliveryAttemptAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderDeliveryAttemptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderDeliveryAttemptAllUpdatablePropertiesEquals(OrderDeliveryAttempt expected, OrderDeliveryAttempt actual) {
        assertOrderDeliveryAttemptUpdatableFieldsEquals(expected, actual);
        assertOrderDeliveryAttemptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderDeliveryAttemptAutoGeneratedPropertiesEquals(OrderDeliveryAttempt expected, OrderDeliveryAttempt actual) {
        assertThat(expected)
            .as("Verify OrderDeliveryAttempt auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderDeliveryAttemptUpdatableFieldsEquals(OrderDeliveryAttempt expected, OrderDeliveryAttempt actual) {
        assertThat(expected)
            .as("Verify OrderDeliveryAttempt relevant properties")
            .satisfies(e -> assertThat(e.getAttemptNo()).as("check attemptNo").isEqualTo(actual.getAttemptNo()))
            .satisfies(e -> assertThat(e.getAttemptAt()).as("check attemptAt").isEqualTo(actual.getAttemptAt()))
            .satisfies(e -> assertThat(e.getResult()).as("check result").isEqualTo(actual.getResult()))
            .satisfies(e -> assertThat(e.getReason()).as("check reason").isEqualTo(actual.getReason()))
            .satisfies(e -> assertThat(e.getHandledByUsername()).as("check handledByUsername").isEqualTo(actual.getHandledByUsername()))
            .satisfies(e -> assertThat(e.getDeliveryPartner()).as("check deliveryPartner").isEqualTo(actual.getDeliveryPartner()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderDeliveryAttemptUpdatableRelationshipsEquals(OrderDeliveryAttempt expected, OrderDeliveryAttempt actual) {
        assertThat(expected)
            .as("Verify OrderDeliveryAttempt relationships")
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()));
    }
}
