package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderReturnRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderReturnRequestAllPropertiesEquals(OrderReturnRequest expected, OrderReturnRequest actual) {
        assertOrderReturnRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderReturnRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderReturnRequestAllUpdatablePropertiesEquals(OrderReturnRequest expected, OrderReturnRequest actual) {
        assertOrderReturnRequestUpdatableFieldsEquals(expected, actual);
        assertOrderReturnRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderReturnRequestAutoGeneratedPropertiesEquals(OrderReturnRequest expected, OrderReturnRequest actual) {
        assertThat(expected)
            .as("Verify OrderReturnRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderReturnRequestUpdatableFieldsEquals(OrderReturnRequest expected, OrderReturnRequest actual) {
        assertThat(expected)
            .as("Verify OrderReturnRequest relevant properties")
            .satisfies(e -> assertThat(e.getReason()).as("check reason").isEqualTo(actual.getReason()))
            .satisfies(e ->
                assertThat(e.getRequestedByUsername()).as("check requestedByUsername").isEqualTo(actual.getRequestedByUsername())
            )
            .satisfies(e -> assertThat(e.getRequestedAt()).as("check requestedAt").isEqualTo(actual.getRequestedAt()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getDecidedByUsername()).as("check decidedByUsername").isEqualTo(actual.getDecidedByUsername()))
            .satisfies(e -> assertThat(e.getDecidedAt()).as("check decidedAt").isEqualTo(actual.getDecidedAt()))
            .satisfies(e -> assertThat(e.getDecisionNote()).as("check decisionNote").isEqualTo(actual.getDecisionNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderReturnRequestUpdatableRelationshipsEquals(OrderReturnRequest expected, OrderReturnRequest actual) {
        // empty method
    }
}
