package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderEventAllPropertiesEquals(OrderEvent expected, OrderEvent actual) {
        assertOrderEventAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderEventAllUpdatablePropertiesEquals(OrderEvent expected, OrderEvent actual) {
        assertOrderEventUpdatableFieldsEquals(expected, actual);
        assertOrderEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderEventAutoGeneratedPropertiesEquals(OrderEvent expected, OrderEvent actual) {
        assertThat(expected)
            .as("Verify OrderEvent auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderEventUpdatableFieldsEquals(OrderEvent expected, OrderEvent actual) {
        assertThat(expected)
            .as("Verify OrderEvent relevant properties")
            .satisfies(e -> assertThat(e.getEventAt()).as("check eventAt").isEqualTo(actual.getEventAt()))
            .satisfies(e -> assertThat(e.getAction()).as("check action").isEqualTo(actual.getAction()))
            .satisfies(e -> assertThat(e.getDetail()).as("check detail").isEqualTo(actual.getDetail()))
            .satisfies(e -> assertThat(e.getActorUsername()).as("check actorUsername").isEqualTo(actual.getActorUsername()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderEventUpdatableRelationshipsEquals(OrderEvent expected, OrderEvent actual) {
        assertThat(expected)
            .as("Verify OrderEvent relationships")
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()));
    }
}
