package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderLegAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLegAllPropertiesEquals(OrderLeg expected, OrderLeg actual) {
        assertOrderLegAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderLegAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLegAllUpdatablePropertiesEquals(OrderLeg expected, OrderLeg actual) {
        assertOrderLegUpdatableFieldsEquals(expected, actual);
        assertOrderLegUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLegAutoGeneratedPropertiesEquals(OrderLeg expected, OrderLeg actual) {
        assertThat(expected)
            .as("Verify OrderLeg auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLegUpdatableFieldsEquals(OrderLeg expected, OrderLeg actual) {
        assertThat(expected)
            .as("Verify OrderLeg relevant properties")
            .satisfies(e -> assertThat(e.getLegIndex()).as("check legIndex").isEqualTo(actual.getLegIndex()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getDepartedAt()).as("check departedAt").isEqualTo(actual.getDepartedAt()))
            .satisfies(e -> assertThat(e.getArrivedAt()).as("check arrivedAt").isEqualTo(actual.getArrivedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderLegUpdatableRelationshipsEquals(OrderLeg expected, OrderLeg actual) {
        assertThat(expected)
            .as("Verify OrderLeg relationships")
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()))
            .satisfies(e -> assertThat(e.getFromOffice()).as("check fromOffice").isEqualTo(actual.getFromOffice()))
            .satisfies(e -> assertThat(e.getToOffice()).as("check toOffice").isEqualTo(actual.getToOffice()))
            .satisfies(e -> assertThat(e.getTrip()).as("check trip").isEqualTo(actual.getTrip()));
    }
}
