package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderPodPhotoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPodPhotoAllPropertiesEquals(OrderPodPhoto expected, OrderPodPhoto actual) {
        assertOrderPodPhotoAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderPodPhotoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPodPhotoAllUpdatablePropertiesEquals(OrderPodPhoto expected, OrderPodPhoto actual) {
        assertOrderPodPhotoUpdatableFieldsEquals(expected, actual);
        assertOrderPodPhotoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPodPhotoAutoGeneratedPropertiesEquals(OrderPodPhoto expected, OrderPodPhoto actual) {
        assertThat(expected)
            .as("Verify OrderPodPhoto auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPodPhotoUpdatableFieldsEquals(OrderPodPhoto expected, OrderPodPhoto actual) {
        assertThat(expected)
            .as("Verify OrderPodPhoto relevant properties")
            .satisfies(e -> assertThat(e.getPhotoUrl()).as("check photoUrl").isEqualTo(actual.getPhotoUrl()))
            .satisfies(e -> assertThat(e.getCapturedAt()).as("check capturedAt").isEqualTo(actual.getCapturedAt()))
            .satisfies(e -> assertThat(e.getCapturedByUsername()).as("check capturedByUsername").isEqualTo(actual.getCapturedByUsername()))
            .satisfies(e -> assertThat(e.getSequenceNo()).as("check sequenceNo").isEqualTo(actual.getSequenceNo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderPodPhotoUpdatableRelationshipsEquals(OrderPodPhoto expected, OrderPodPhoto actual) {
        assertThat(expected)
            .as("Verify OrderPodPhoto relationships")
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()));
    }
}
