package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderIssueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderIssueAllPropertiesEquals(OrderIssue expected, OrderIssue actual) {
        assertOrderIssueAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderIssueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderIssueAllUpdatablePropertiesEquals(OrderIssue expected, OrderIssue actual) {
        assertOrderIssueUpdatableFieldsEquals(expected, actual);
        assertOrderIssueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderIssueAutoGeneratedPropertiesEquals(OrderIssue expected, OrderIssue actual) {
        assertThat(expected)
            .as("Verify OrderIssue auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderIssueUpdatableFieldsEquals(OrderIssue expected, OrderIssue actual) {
        assertThat(expected)
            .as("Verify OrderIssue relevant properties")
            .satisfies(e -> assertThat(e.getIssueType()).as("check issueType").isEqualTo(actual.getIssueType()))
            .satisfies(e -> assertThat(e.getIssueStatus()).as("check issueStatus").isEqualTo(actual.getIssueStatus()))
            .satisfies(e -> assertThat(e.getReason()).as("check reason").isEqualTo(actual.getReason()))
            .satisfies(e -> assertThat(e.getOpenedAt()).as("check openedAt").isEqualTo(actual.getOpenedAt()))
            .satisfies(e -> assertThat(e.getOpenedByUsername()).as("check openedByUsername").isEqualTo(actual.getOpenedByUsername()))
            .satisfies(e -> assertThat(e.getResolvedAt()).as("check resolvedAt").isEqualTo(actual.getResolvedAt()))
            .satisfies(e -> assertThat(e.getResolvedByUsername()).as("check resolvedByUsername").isEqualTo(actual.getResolvedByUsername()))
            .satisfies(e -> assertThat(e.getResolutionNote()).as("check resolutionNote").isEqualTo(actual.getResolutionNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderIssueUpdatableRelationshipsEquals(OrderIssue expected, OrderIssue actual) {
        // empty method
    }
}
