package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PricingChangeLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingChangeLogAllPropertiesEquals(PricingChangeLog expected, PricingChangeLog actual) {
        assertPricingChangeLogAutoGeneratedPropertiesEquals(expected, actual);
        assertPricingChangeLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingChangeLogAllUpdatablePropertiesEquals(PricingChangeLog expected, PricingChangeLog actual) {
        assertPricingChangeLogUpdatableFieldsEquals(expected, actual);
        assertPricingChangeLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingChangeLogAutoGeneratedPropertiesEquals(PricingChangeLog expected, PricingChangeLog actual) {
        assertThat(expected)
            .as("Verify PricingChangeLog auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingChangeLogUpdatableFieldsEquals(PricingChangeLog expected, PricingChangeLog actual) {
        assertThat(expected)
            .as("Verify PricingChangeLog relevant properties")
            .satisfies(e -> assertThat(e.getChangedAt()).as("check changedAt").isEqualTo(actual.getChangedAt()))
            .satisfies(e -> assertThat(e.getChangedByUsername()).as("check changedByUsername").isEqualTo(actual.getChangedByUsername()))
            .satisfies(e -> assertThat(e.getBeforeJson()).as("check beforeJson").isEqualTo(actual.getBeforeJson()))
            .satisfies(e -> assertThat(e.getAfterJson()).as("check afterJson").isEqualTo(actual.getAfterJson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingChangeLogUpdatableRelationshipsEquals(PricingChangeLog expected, PricingChangeLog actual) {
        assertThat(expected)
            .as("Verify PricingChangeLog relationships")
            .satisfies(e -> assertThat(e.getPricingRule()).as("check pricingRule").isEqualTo(actual.getPricingRule()));
    }
}
