package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PricingRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingRuleAllPropertiesEquals(PricingRule expected, PricingRule actual) {
        assertPricingRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertPricingRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingRuleAllUpdatablePropertiesEquals(PricingRule expected, PricingRule actual) {
        assertPricingRuleUpdatableFieldsEquals(expected, actual);
        assertPricingRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingRuleAutoGeneratedPropertiesEquals(PricingRule expected, PricingRule actual) {
        assertThat(expected)
            .as("Verify PricingRule auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingRuleUpdatableFieldsEquals(PricingRule expected, PricingRule actual) {
        assertThat(expected)
            .as("Verify PricingRule relevant properties")
            .satisfies(e -> assertThat(e.getRuleCode()).as("check ruleCode").isEqualTo(actual.getRuleCode()))
            .satisfies(e -> assertThat(e.getTierLabel()).as("check tierLabel").isEqualTo(actual.getTierLabel()))
            .satisfies(e -> assertThat(e.getMinKg()).as("check minKg").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getMinKg()))
            .satisfies(e -> assertThat(e.getMaxKg()).as("check maxKg").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getMaxKg()))
            .satisfies(e ->
                assertThat(e.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getUnitPrice())
            )
            .satisfies(e ->
                assertThat(e.getSurchargeAmount())
                    .as("check surchargeAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getSurchargeAmount())
            )
            .satisfies(e -> assertThat(e.getDimDivisor()).as("check dimDivisor").isEqualTo(actual.getDimDivisor()))
            .satisfies(e -> assertThat(e.getKmMin()).as("check kmMin").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getKmMin()))
            .satisfies(e -> assertThat(e.getKmRate()).as("check kmRate").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getKmRate()))
            .satisfies(e -> assertThat(e.getStepGram()).as("check stepGram").isEqualTo(actual.getStepGram()))
            .satisfies(e ->
                assertThat(e.getAddFeeAmount())
                    .as("check addFeeAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getAddFeeAmount())
            )
            .satisfies(e -> assertThat(e.getEffectiveFrom()).as("check effectiveFrom").isEqualTo(actual.getEffectiveFrom()))
            .satisfies(e -> assertThat(e.getEffectiveTo()).as("check effectiveTo").isEqualTo(actual.getEffectiveTo()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingRuleUpdatableRelationshipsEquals(PricingRule expected, PricingRule actual) {
        assertThat(expected)
            .as("Verify PricingRule relationships")
            .satisfies(e -> assertThat(e.getRoute()).as("check route").isEqualTo(actual.getRoute()));
    }
}
