package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProductPriceRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPriceRuleAllPropertiesEquals(ProductPriceRule expected, ProductPriceRule actual) {
        assertProductPriceRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertProductPriceRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPriceRuleAllUpdatablePropertiesEquals(ProductPriceRule expected, ProductPriceRule actual) {
        assertProductPriceRuleUpdatableFieldsEquals(expected, actual);
        assertProductPriceRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPriceRuleAutoGeneratedPropertiesEquals(ProductPriceRule expected, ProductPriceRule actual) {
        assertThat(expected)
            .as("Verify ProductPriceRule auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPriceRuleUpdatableFieldsEquals(ProductPriceRule expected, ProductPriceRule actual) {
        assertThat(expected)
            .as("Verify ProductPriceRule relevant properties")
            .satisfies(e -> assertThat(e.getGroupName()).as("check groupName").isEqualTo(actual.getGroupName()))
            .satisfies(e -> assertThat(e.getProductName()).as("check productName").isEqualTo(actual.getProductName()))
            .satisfies(e ->
                assertThat(e.getCurrentPrice())
                    .as("check currentPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getCurrentPrice())
            )
            .satisfies(e ->
                assertThat(e.getAppliedPrice())
                    .as("check appliedPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getAppliedPrice())
            )
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPriceRuleUpdatableRelationshipsEquals(ProductPriceRule expected, ProductPriceRule actual) {
        // empty method
    }
}
