package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ReceiptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptAllPropertiesEquals(Receipt expected, Receipt actual) {
        assertReceiptAutoGeneratedPropertiesEquals(expected, actual);
        assertReceiptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptAllUpdatablePropertiesEquals(Receipt expected, Receipt actual) {
        assertReceiptUpdatableFieldsEquals(expected, actual);
        assertReceiptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptAutoGeneratedPropertiesEquals(Receipt expected, Receipt actual) {
        assertThat(expected)
            .as("Verify Receipt auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptUpdatableFieldsEquals(Receipt expected, Receipt actual) {
        assertThat(expected)
            .as("Verify Receipt relevant properties")
            .satisfies(e -> assertThat(e.getReceiptCode()).as("check receiptCode").isEqualTo(actual.getReceiptCode()))
            .satisfies(e -> assertThat(e.getPayerName()).as("check payerName").isEqualTo(actual.getPayerName()))
            .satisfies(e -> assertThat(e.getPayerCode()).as("check payerCode").isEqualTo(actual.getPayerCode()))
            .satisfies(e ->
                assertThat(e.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getTotalAmount())
            )
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedByUsername()).as("check createdByUsername").isEqualTo(actual.getCreatedByUsername()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptUpdatableRelationshipsEquals(Receipt expected, Receipt actual) {
        assertThat(expected)
            .as("Verify Receipt relationships")
            .satisfies(e -> assertThat(e.getOffice()).as("check office").isEqualTo(actual.getOffice()));
    }
}
