package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ReceiptOrderLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptOrderLineAllPropertiesEquals(ReceiptOrderLine expected, ReceiptOrderLine actual) {
        assertReceiptOrderLineAutoGeneratedPropertiesEquals(expected, actual);
        assertReceiptOrderLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptOrderLineAllUpdatablePropertiesEquals(ReceiptOrderLine expected, ReceiptOrderLine actual) {
        assertReceiptOrderLineUpdatableFieldsEquals(expected, actual);
        assertReceiptOrderLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptOrderLineAutoGeneratedPropertiesEquals(ReceiptOrderLine expected, ReceiptOrderLine actual) {
        assertThat(expected)
            .as("Verify ReceiptOrderLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptOrderLineUpdatableFieldsEquals(ReceiptOrderLine expected, ReceiptOrderLine actual) {
        assertThat(expected)
            .as("Verify ReceiptOrderLine relevant properties")
            .satisfies(e ->
                assertThat(e.getAmountCollected())
                    .as("check amountCollected")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getAmountCollected())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceiptOrderLineUpdatableRelationshipsEquals(ReceiptOrderLine expected, ReceiptOrderLine actual) {
        assertThat(expected)
            .as("Verify ReceiptOrderLine relationships")
            .satisfies(e -> assertThat(e.getReceipt()).as("check receipt").isEqualTo(actual.getReceipt()))
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()));
    }
}
