package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RouteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteAllPropertiesEquals(Route expected, Route actual) {
        assertRouteAutoGeneratedPropertiesEquals(expected, actual);
        assertRouteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteAllUpdatablePropertiesEquals(Route expected, Route actual) {
        assertRouteUpdatableFieldsEquals(expected, actual);
        assertRouteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteAutoGeneratedPropertiesEquals(Route expected, Route actual) {
        assertThat(expected)
            .as("Verify Route auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteUpdatableFieldsEquals(Route expected, Route actual) {
        assertThat(expected)
            .as("Verify Route relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteUpdatableRelationshipsEquals(Route expected, Route actual) {
        assertThat(expected)
            .as("Verify Route relationships")
            .satisfies(e -> assertThat(e.getFromOffice()).as("check fromOffice").isEqualTo(actual.getFromOffice()))
            .satisfies(e -> assertThat(e.getToOffice()).as("check toOffice").isEqualTo(actual.getToOffice()));
    }
}
