package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentOrderAllPropertiesEquals(ShipmentOrder expected, ShipmentOrder actual) {
        assertShipmentOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentOrderAllUpdatablePropertiesEquals(ShipmentOrder expected, ShipmentOrder actual) {
        assertShipmentOrderUpdatableFieldsEquals(expected, actual);
        assertShipmentOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentOrderAutoGeneratedPropertiesEquals(ShipmentOrder expected, ShipmentOrder actual) {
        assertThat(expected)
            .as("Verify ShipmentOrder auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentOrderUpdatableFieldsEquals(ShipmentOrder expected, ShipmentOrder actual) {
        assertThat(expected)
            .as("Verify ShipmentOrder relevant properties")
            .satisfies(e -> assertThat(e.getOrderCode()).as("check orderCode").isEqualTo(actual.getOrderCode()))
            .satisfies(e -> assertThat(e.getDraftCode()).as("check draftCode").isEqualTo(actual.getDraftCode()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getForwardStage()).as("check forwardStage").isEqualTo(actual.getForwardStage()))
            .satisfies(e -> assertThat(e.getReturnStage()).as("check returnStage").isEqualTo(actual.getReturnStage()))
            .satisfies(e -> assertThat(e.getPaymentTerm()).as("check paymentTerm").isEqualTo(actual.getPaymentTerm()))
            .satisfies(e -> assertThat(e.getGoodsType()).as("check goodsType").isEqualTo(actual.getGoodsType()))
            .satisfies(e -> assertThat(e.getServiceType()).as("check serviceType").isEqualTo(actual.getServiceType()))
            .satisfies(e -> assertThat(e.getSenderName()).as("check senderName").isEqualTo(actual.getSenderName()))
            .satisfies(e -> assertThat(e.getSenderPhone()).as("check senderPhone").isEqualTo(actual.getSenderPhone()))
            .satisfies(e -> assertThat(e.getReceiverName()).as("check receiverName").isEqualTo(actual.getReceiverName()))
            .satisfies(e -> assertThat(e.getReceiverPhone()).as("check receiverPhone").isEqualTo(actual.getReceiverPhone()))
            .satisfies(e -> assertThat(e.getDeliveryAddress()).as("check deliveryAddress").isEqualTo(actual.getDeliveryAddress()))
            .satisfies(e -> assertThat(e.getPickupAddress()).as("check pickupAddress").isEqualTo(actual.getPickupAddress()))
            .satisfies(e -> assertThat(e.getHomePickup()).as("check homePickup").isEqualTo(actual.getHomePickup()))
            .satisfies(e -> assertThat(e.getHomeDelivery()).as("check homeDelivery").isEqualTo(actual.getHomeDelivery()))
            .satisfies(e -> assertThat(e.getQrDropOff()).as("check qrDropOff").isEqualTo(actual.getQrDropOff()))
            .satisfies(e ->
                assertThat(e.getPickupStaffUsername()).as("check pickupStaffUsername").isEqualTo(actual.getPickupStaffUsername())
            )
            .satisfies(e -> assertThat(e.getPickingAt()).as("check pickingAt").isEqualTo(actual.getPickingAt()))
            .satisfies(e -> assertThat(e.getPickedUpAt()).as("check pickedUpAt").isEqualTo(actual.getPickedUpAt()))
            .satisfies(e -> assertThat(e.getReceiverActualName()).as("check receiverActualName").isEqualTo(actual.getReceiverActualName()))
            .satisfies(e ->
                assertThat(e.getReceiverActualPhone()).as("check receiverActualPhone").isEqualTo(actual.getReceiverActualPhone())
            )
            .satisfies(e ->
                assertThat(e.getWeightKg()).as("check weightKg").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getWeightKg())
            )
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getDimensionsText()).as("check dimensionsText").isEqualTo(actual.getDimensionsText()))
            .satisfies(e ->
                assertThat(e.getFareAmount()).as("check fareAmount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getFareAmount())
            )
            .satisfies(e ->
                assertThat(e.getPickupFeeAmount())
                    .as("check pickupFeeAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getPickupFeeAmount())
            )
            .satisfies(e ->
                assertThat(e.getDeliveryFeeAmount())
                    .as("check deliveryFeeAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getDeliveryFeeAmount())
            )
            .satisfies(e ->
                assertThat(e.getPartnerFeeAmount())
                    .as("check partnerFeeAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getPartnerFeeAmount())
            )
            .satisfies(e ->
                assertThat(e.getPaidAmount()).as("check paidAmount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPaidAmount())
            )
            .satisfies(e -> assertThat(e.getShelfNumber()).as("check shelfNumber").isEqualTo(actual.getShelfNumber()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()))
            .satisfies(e -> assertThat(e.getCancelReason()).as("check cancelReason").isEqualTo(actual.getCancelReason()))
            .satisfies(e -> assertThat(e.getLabelPrintedAt()).as("check labelPrintedAt").isEqualTo(actual.getLabelPrintedAt()))
            .satisfies(e -> assertThat(e.getLabelReprintCount()).as("check labelReprintCount").isEqualTo(actual.getLabelReprintCount()))
            .satisfies(e -> assertThat(e.getFailCount()).as("check failCount").isEqualTo(actual.getFailCount()))
            .satisfies(e -> assertThat(e.getPartnerCode()).as("check partnerCode").isEqualTo(actual.getPartnerCode()))
            .satisfies(e ->
                assertThat(e.getPaymentPercent())
                    .as("check paymentPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getPaymentPercent())
            )
            .satisfies(e ->
                assertThat(e.getPublicTrackingAllowed()).as("check publicTrackingAllowed").isEqualTo(actual.getPublicTrackingAllowed())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentOrderUpdatableRelationshipsEquals(ShipmentOrder expected, ShipmentOrder actual) {
        assertThat(expected)
            .as("Verify ShipmentOrder relationships")
            .satisfies(e -> assertThat(e.getIssue()).as("check issue").isEqualTo(actual.getIssue()))
            .satisfies(e -> assertThat(e.getReturnRequest()).as("check returnRequest").isEqualTo(actual.getReturnRequest()))
            .satisfies(e ->
                assertThat(e.getFareAdjustmentRequest()).as("check fareAdjustmentRequest").isEqualTo(actual.getFareAdjustmentRequest())
            )
            .satisfies(e -> assertThat(e.getSenderCustomer()).as("check senderCustomer").isEqualTo(actual.getSenderCustomer()))
            .satisfies(e -> assertThat(e.getFromOffice()).as("check fromOffice").isEqualTo(actual.getFromOffice()))
            .satisfies(e -> assertThat(e.getToOffice()).as("check toOffice").isEqualTo(actual.getToOffice()))
            .satisfies(e -> assertThat(e.getHubOffice()).as("check hubOffice").isEqualTo(actual.getHubOffice()))
            .satisfies(e -> assertThat(e.getFinalToOffice()).as("check finalToOffice").isEqualTo(actual.getFinalToOffice()))
            .satisfies(e -> assertThat(e.getCurrentTrip()).as("check currentTrip").isEqualTo(actual.getCurrentTrip()));
    }
}
