package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StaffProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffProfileAllPropertiesEquals(StaffProfile expected, StaffProfile actual) {
        assertStaffProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertStaffProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffProfileAllUpdatablePropertiesEquals(StaffProfile expected, StaffProfile actual) {
        assertStaffProfileUpdatableFieldsEquals(expected, actual);
        assertStaffProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffProfileAutoGeneratedPropertiesEquals(StaffProfile expected, StaffProfile actual) {
        assertThat(expected)
            .as("Verify StaffProfile auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffProfileUpdatableFieldsEquals(StaffProfile expected, StaffProfile actual) {
        assertThat(expected)
            .as("Verify StaffProfile relevant properties")
            .satisfies(e -> assertThat(e.getStaffCode()).as("check staffCode").isEqualTo(actual.getStaffCode()))
            .satisfies(e -> assertThat(e.getUserLogin()).as("check userLogin").isEqualTo(actual.getUserLogin()))
            .satisfies(e -> assertThat(e.getDisplayName()).as("check displayName").isEqualTo(actual.getDisplayName()))
            .satisfies(e -> assertThat(e.getRoleCode()).as("check roleCode").isEqualTo(actual.getRoleCode()))
            .satisfies(e -> assertThat(e.getScopeAllOffices()).as("check scopeAllOffices").isEqualTo(actual.getScopeAllOffices()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffProfileUpdatableRelationshipsEquals(StaffProfile expected, StaffProfile actual) {
        assertThat(expected)
            .as("Verify StaffProfile relationships")
            .satisfies(e -> assertThat(e.getOffice()).as("check office").isEqualTo(actual.getOffice()));
    }
}
