package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SurchargePolicyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurchargePolicyAllPropertiesEquals(SurchargePolicy expected, SurchargePolicy actual) {
        assertSurchargePolicyAutoGeneratedPropertiesEquals(expected, actual);
        assertSurchargePolicyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurchargePolicyAllUpdatablePropertiesEquals(SurchargePolicy expected, SurchargePolicy actual) {
        assertSurchargePolicyUpdatableFieldsEquals(expected, actual);
        assertSurchargePolicyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurchargePolicyAutoGeneratedPropertiesEquals(SurchargePolicy expected, SurchargePolicy actual) {
        assertThat(expected)
            .as("Verify SurchargePolicy auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurchargePolicyUpdatableFieldsEquals(SurchargePolicy expected, SurchargePolicy actual) {
        assertThat(expected)
            .as("Verify SurchargePolicy relevant properties")
            .satisfies(e ->
                assertThat(e.getHomeDeliveryEnabled()).as("check homeDeliveryEnabled").isEqualTo(actual.getHomeDeliveryEnabled())
            )
            .satisfies(e ->
                assertThat(e.getDefaultHomeDeliveryAmount())
                    .as("check defaultHomeDeliveryAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getDefaultHomeDeliveryAmount())
            )
            .satisfies(e -> assertThat(e.getCodEnabled()).as("check codEnabled").isEqualTo(actual.getCodEnabled()))
            .satisfies(e ->
                assertThat(e.getCodPercent()).as("check codPercent").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getCodPercent())
            )
            .satisfies(e ->
                assertThat(e.getCodMinFee()).as("check codMinFee").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getCodMinFee())
            )
            .satisfies(e -> assertThat(e.getStorageEnabled()).as("check storageEnabled").isEqualTo(actual.getStorageEnabled()))
            .satisfies(e -> assertThat(e.getStorageFreeDays()).as("check storageFreeDays").isEqualTo(actual.getStorageFreeDays()))
            .satisfies(e ->
                assertThat(e.getStorageFeePerDay())
                    .as("check storageFeePerDay")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getStorageFeePerDay())
            )
            .satisfies(e -> assertThat(e.getInsuranceEnabled()).as("check insuranceEnabled").isEqualTo(actual.getInsuranceEnabled()))
            .satisfies(e ->
                assertThat(e.getInsuranceThreshold())
                    .as("check insuranceThreshold")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getInsuranceThreshold())
            )
            .satisfies(e ->
                assertThat(e.getInsurancePercentUnder())
                    .as("check insurancePercentUnder")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getInsurancePercentUnder())
            )
            .satisfies(e ->
                assertThat(e.getInsurancePercentOver())
                    .as("check insurancePercentOver")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getInsurancePercentOver())
            )
            .satisfies(e -> assertThat(e.getRefundEnabled()).as("check refundEnabled").isEqualTo(actual.getRefundEnabled()))
            .satisfies(e ->
                assertThat(e.getRefundPercent())
                    .as("check refundPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getRefundPercent())
            )
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurchargePolicyUpdatableRelationshipsEquals(SurchargePolicy expected, SurchargePolicy actual) {
        // empty method
    }
}
