package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TripAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAllPropertiesEquals(Trip expected, Trip actual) {
        assertTripAutoGeneratedPropertiesEquals(expected, actual);
        assertTripAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAllUpdatablePropertiesEquals(Trip expected, Trip actual) {
        assertTripUpdatableFieldsEquals(expected, actual);
        assertTripUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripAutoGeneratedPropertiesEquals(Trip expected, Trip actual) {
        assertThat(expected)
            .as("Verify Trip auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripUpdatableFieldsEquals(Trip expected, Trip actual) {
        assertThat(expected)
            .as("Verify Trip relevant properties")
            .satisfies(e -> assertThat(e.getTripCode()).as("check tripCode").isEqualTo(actual.getTripCode()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getDepartAt()).as("check departAt").isEqualTo(actual.getDepartAt()))
            .satisfies(e -> assertThat(e.getLoadedCount()).as("check loadedCount").isEqualTo(actual.getLoadedCount()))
            .satisfies(e -> assertThat(e.getScannedCount()).as("check scannedCount").isEqualTo(actual.getScannedCount()))
            .satisfies(e -> assertThat(e.getClosedAt()).as("check closedAt").isEqualTo(actual.getClosedAt()))
            .satisfies(e -> assertThat(e.getForceClosed()).as("check forceClosed").isEqualTo(actual.getForceClosed()))
            .satisfies(e -> assertThat(e.getForceCloseReason()).as("check forceCloseReason").isEqualTo(actual.getForceCloseReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripUpdatableRelationshipsEquals(Trip expected, Trip actual) {
        assertThat(expected)
            .as("Verify Trip relationships")
            .satisfies(e -> assertThat(e.getOffice()).as("check office").isEqualTo(actual.getOffice()))
            .satisfies(e -> assertThat(e.getRoute()).as("check route").isEqualTo(actual.getRoute()))
            .satisfies(e -> assertThat(e.getVehicle()).as("check vehicle").isEqualTo(actual.getVehicle()))
            .satisfies(e -> assertThat(e.getDriver()).as("check driver").isEqualTo(actual.getDriver()));
    }
}
