package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TripOrderAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripOrderAssignmentAllPropertiesEquals(TripOrderAssignment expected, TripOrderAssignment actual) {
        assertTripOrderAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertTripOrderAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripOrderAssignmentAllUpdatablePropertiesEquals(TripOrderAssignment expected, TripOrderAssignment actual) {
        assertTripOrderAssignmentUpdatableFieldsEquals(expected, actual);
        assertTripOrderAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripOrderAssignmentAutoGeneratedPropertiesEquals(TripOrderAssignment expected, TripOrderAssignment actual) {
        assertThat(expected)
            .as("Verify TripOrderAssignment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripOrderAssignmentUpdatableFieldsEquals(TripOrderAssignment expected, TripOrderAssignment actual) {
        assertThat(expected)
            .as("Verify TripOrderAssignment relevant properties")
            .satisfies(e -> assertThat(e.getAssignmentStatus()).as("check assignmentStatus").isEqualTo(actual.getAssignmentStatus()))
            .satisfies(e -> assertThat(e.getScannedAt()).as("check scannedAt").isEqualTo(actual.getScannedAt()))
            .satisfies(e -> assertThat(e.getLoadedAt()).as("check loadedAt").isEqualTo(actual.getLoadedAt()))
            .satisfies(e -> assertThat(e.getRemovedAt()).as("check removedAt").isEqualTo(actual.getRemovedAt()))
            .satisfies(e -> assertThat(e.getRemark()).as("check remark").isEqualTo(actual.getRemark()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripOrderAssignmentUpdatableRelationshipsEquals(TripOrderAssignment expected, TripOrderAssignment actual) {
        assertThat(expected)
            .as("Verify TripOrderAssignment relationships")
            .satisfies(e -> assertThat(e.getTrip()).as("check trip").isEqualTo(actual.getTrip()))
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()));
    }
}
